-- AlterTable
ALTER TABLE "Amenity" ALTER COLUMN "price" SET DEFAULT '0',
ALTER COLUMN "price" SET DATA TYPE TEXT,
ALTER COLUMN "footage" SET DEFAULT '0',
ALTER COLUMN "footage" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Expense" ALTER COLUMN "cost" SET DEFAULT '0',
ALTER COLUMN "cost" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "LivingSpace" ALTER COLUMN "footage" SET DEFAULT '0',
ALTER COLUMN "footage" SET DATA TYPE TEXT;
